### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by kingaimaster94** [flashbots/web3-flashbots#99]
I tried to send_bundle function on sepolia net.
But these error occurs.
"""
Traceback (most recent call last):
  File "/home/Eth-bundle/./bundle.py", line 199, in <module>
    main()
  File "/home/Eth-bundle/./bundle.py", line 191, in main
    tx = buy_bundle(private_keys, token_address, [0.005, 0.005])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Eth-bundle/./bundle.py", line 157, in buy_bundle
    send_result = w3.flashbots.sendRawBundle(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Eth-bundle/env/lib/python3.11/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Eth-bundle/env/lib/python3.11/site-packages/web3/manager.py", line 330, in request_blocking
    return self.formatted_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Eth-bundle/env/lib/python3.11/site-packages/web3/manager.py", line 293, in formatted_response
    raise ValueError(error)
ValueError: {'code': -32000, 'message': 'internal server error'}
"""

**Comment by kingaimaster94** [comment]
PROVIDER_URL=https://ethereum-sepolia-rpc.publicnode.com

**Comment by sasiyaluba** [comment]
so you solve it?I met same

**Comment by kingaimaster94** [comment]
I didn't solve it yet.

**Comment by blockchain-src** [comment]
我也遇到同样问题
